// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "lucien",
            "url": "none",
            "email": "none"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/community/create": {
            "post": {
                "description": "创建社区信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "社区接口"
                ],
                "summary": "创建社区信息接口",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponseSuccess"
                        }
                    }
                }
            }
        },
        "/community/show/{community_id}": {
            "get": {
                "description": "查询社区分类详情信息返回列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "社区接口"
                ],
                "summary": "查询社区分类详情信息接口",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "社区ID",
                        "name": "community_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponseCommunityDetail"
                        }
                    }
                }
            }
        },
        "/posts/post": {
            "post": {
                "description": "用户发布新帖子",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "帖子接口"
                ],
                "summary": "发布帖子",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "帖子内容",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.PostCreateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponseSuccess"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponseError"
                        }
                    }
                }
            }
        },
        "/posts/search": {
            "get": {
                "description": "可按社区、时间、分数排序查询帖子",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "帖子接口"
                ],
                "summary": "搜索/排序帖子列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page_num",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "排序方式(time/score)",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "社区ID",
                        "name": "community_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponsePostList"
                        }
                    }
                }
            }
        },
        "/posts/show": {
            "get": {
                "description": "分页获取帖子列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "帖子接口"
                ],
                "summary": "获取帖子列表分页",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page_num",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponsePostList"
                        }
                    }
                }
            }
        },
        "/posts/vote": {
            "post": {
                "description": "用户对帖子进行投票（点赞/点踩）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "帖子接口"
                ],
                "summary": "用户投票",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "投票参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.PostVoteDataReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponseSuccess"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponseError"
                        }
                    }
                }
            }
        },
        "/posts/{post_id}": {
            "get": {
                "description": "根据帖子ID获取详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "帖子接口"
                ],
                "summary": "获取帖子详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "帖子ID",
                        "name": "post_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponsePostDetail"
                        }
                    }
                }
            }
        },
        "/show/community": {
            "get": {
                "description": "查询社区信息返回列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "社区接口"
                ],
                "summary": "查询社区信息接口",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponseCommunityList"
                        }
                    }
                }
            }
        },
        "/user/avatar": {
            "post": {
                "description": "为当前登录用户上传头像",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户接口"
                ],
                "summary": "上传头像",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "头像文件",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponseSuccess"
                        }
                    }
                }
            }
        },
        "/user/email/login": {
            "post": {
                "description": "使用邮箱和验证码登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户接口"
                ],
                "summary": "邮箱登录",
                "parameters": [
                    {
                        "description": "邮箱登录信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.UserLoginEmailReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponseUserLogin"
                        }
                    }
                }
            }
        },
        "/user/email/send": {
            "post": {
                "description": "发送用于绑定或解绑邮箱的验证码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户接口"
                ],
                "summary": "发送绑定/解绑邮箱验证码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "操作信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.UserSendEmailReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponseSuccess"
                        }
                    }
                }
            }
        },
        "/user/email/valid": {
            "post": {
                "description": "验证邮箱验证码以完成绑定或解绑",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户接口"
                ],
                "summary": "验证邮箱",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "验证信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.UserVaildEmail"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponseSuccess"
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "description": "用户名密码登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户接口"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.UserLoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponseUserLogin"
                        }
                    }
                }
            }
        },
        "/user/signup": {
            "post": {
                "description": "用户注册",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户接口"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "注册信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.UserSignUpReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponseUserLogin"
                        }
                    }
                }
            }
        },
        "/user/update": {
            "put": {
                "description": "更新当前登录用户的信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户接口"
                ],
                "summary": "更新用户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "更新信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.UserUpdateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponseSuccess"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.SwaggerCommunity": {
            "description": "社区信息",
            "type": "object",
            "properties": {
                "community_id": {
                    "type": "integer"
                },
                "community_name": {
                    "type": "string"
                },
                "introduction": {
                    "type": "string"
                }
            }
        },
        "controller.SwaggerPost": {
            "description": "帖子信息",
            "type": "object",
            "properties": {
                "author_id": {
                    "type": "integer"
                },
                "community_id": {
                    "type": "integer"
                },
                "content": {
                    "type": "string"
                },
                "post_id": {
                    "type": "integer"
                },
                "status": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "controller.SwaggerUser": {
            "description": "用户信息",
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "controller._ResponseCommunityDetail": {
            "description": "社区详情响应",
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/controller.SwaggerCommunity"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "controller._ResponseCommunityList": {
            "description": "社区列表响应",
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controller.SwaggerCommunity"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "controller._ResponseError": {
            "description": "通用错误响应",
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "controller._ResponsePostDetail": {
            "description": "帖子详情响应",
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/controller.SwaggerPost"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "controller._ResponsePostList": {
            "description": "帖子列表响应",
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controller.SwaggerPost"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "controller._ResponseSuccess": {
            "description": "通用成功响应",
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "controller._ResponseUserLogin": {
            "description": "用户登录响应",
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/controller.SwaggerUser"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "types.PostCreateReq": {
            "type": "object",
            "required": [
                "community_id",
                "content",
                "title"
            ],
            "properties": {
                "author_id": {
                    "description": "发布者id",
                    "type": "integer"
                },
                "community_id": {
                    "description": "社区id",
                    "type": "integer"
                },
                "content": {
                    "description": "帖子内容",
                    "type": "string"
                },
                "post_id": {
                    "description": "帖子id",
                    "type": "integer"
                },
                "title": {
                    "description": "帖子标题",
                    "type": "string"
                }
            }
        },
        "types.PostVoteDataReq": {
            "type": "object",
            "required": [
                "post_id"
            ],
            "properties": {
                "kind": {
                    "description": "投票帖子赞成(1)\\反对(-1)\\取消投票(0)",
                    "type": "string",
                    "enum": [
                        1,
                        0,
                        -1
                    ],
                    "example": "0"
                },
                "post_id": {
                    "description": "UserID 从请求中获取当前用户",
                    "type": "string",
                    "example": "0"
                }
            }
        },
        "types.UserLoginEmailReq": {
            "type": "object",
            "required": [
                "code",
                "email"
            ],
            "properties": {
                "code": {
                    "description": "邮箱收到的验证码",
                    "type": "string"
                },
                "email": {
                    "description": "用户邮箱",
                    "type": "string"
                }
            }
        },
        "types.UserLoginReq": {
            "type": "object",
            "required": [
                "password",
                "user_name"
            ],
            "properties": {
                "password": {
                    "description": "登录人密码",
                    "type": "string"
                },
                "user_name": {
                    "description": "登录人姓名",
                    "type": "string"
                }
            }
        },
        "types.UserSendEmailCodeReq": {
            "type": "object",
            "required": [
                "email",
                "operation_type"
            ],
            "properties": {
                "email": {
                    "description": "用户邮箱",
                    "type": "string"
                },
                "operation_type": {
                    "description": "邮箱操作类型 3-登录",
                    "type": "integer",
                    "enum": [
                        3
                    ]
                }
            }
        },
        "types.UserSendEmailReq": {
            "type": "object",
            "required": [
                "email",
                "operation_type"
            ],
            "properties": {
                "email": {
                    "description": "用户邮箱",
                    "type": "string"
                },
                "operation_type": {
                    "description": "邮箱操作类型 1-绑定 2-解绑",
                    "type": "integer",
                    "enum": [
                        1,
                        2
                    ]
                }
            }
        },
        "types.UserSignUpReq": {
            "type": "object",
            "required": [
                "gender",
                "password",
                "re_password",
                "user_name"
            ],
            "properties": {
                "age": {
                    "description": "注册人年龄",
                    "type": "integer",
                    "maximum": 130,
                    "minimum": 1
                },
                "avatar": {
                    "description": "// 需要使用自定义校验方法checkDate做参数校验的字段Date\nDate string ` + "`" + `json:\"date\" binding:\"required,datetime=2006-01-02,checkDate\"` + "`" + `",
                    "type": "string"
                },
                "email": {
                    "description": "注册人邮箱",
                    "type": "string"
                },
                "gender": {
                    "description": "注册人性别",
                    "type": "string",
                    "enum": [
                        "男",
                        "女",
                        "未知"
                    ]
                },
                "password": {
                    "description": "注册人密码",
                    "type": "string"
                },
                "re_password": {
                    "description": "注册人重复密码",
                    "type": "string"
                },
                "user_name": {
                    "description": "注册人用户名",
                    "type": "string"
                }
            }
        },
        "types.UserUpdateReq": {
            "type": "object",
            "properties": {
                "age": {
                    "description": "用户年龄",
                    "type": "integer",
                    "maximum": 130,
                    "minimum": 1
                },
                "avatar": {
                    "description": "用户头像",
                    "type": "string"
                },
                "email": {
                    "description": "用户邮箱",
                    "type": "string"
                },
                "gender": {
                    "description": "用户性别",
                    "type": "string",
                    "enum": [
                        "男",
                        "女",
                        "未知"
                    ]
                },
                "new_password": {
                    "description": "新密码",
                    "type": "string"
                },
                "password": {
                    "description": "当前密码",
                    "type": "string"
                },
                "user_name": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "types.UserVaildEmail": {
            "type": "object",
            "required": [
                "code",
                "email",
                "operation_type"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "operation_type": {
                    "type": "integer",
                    "enum": [
                        1,
                        2
                    ]
                },
                "user_id": {
                    "description": "禁止自动绑定",
                    "type": "integer"
                },
                "user_name": {
                    "description": "禁止自动绑定",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1:8081",
	BasePath:         "/api/v1/",
	Schemes:          []string{},
	Title:            "bluebell go-web",
	Description:      "This is a go-web project from https://www.bilibili.com/cheese/play/ep265306",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
